### PR TITLE
Escape single quotes in the styles

### PR DESCRIPTION
**Pull request by sconix**
This adds escaping of the single quotes for the styles as well so that the js file wont brake if the styles contain single quotes.

### CODE REVIEW

**Comment by pablodenadai** [comment]
Could you write a test for that? thanks!

**Comment by sconix** [comment]
I did not write a separate test, but I did add single quotes into the component.css and extended the existing tests to include checking of the proper quote escaping. So I hope that is ok, at least I think its good to check for the escaping in all the tests regarding styles.

**Comment by pablodenadai** [comment]
Thank you!

**Comment by sconix** [comment]
Your welcome. Any estimate when you could release a new public version with this?

**Comment by pablodenadai** [comment]
@sconix Done - see v0.2.2.

**Pull request merged**
