### PR TITLE
Added compress option to api and cli

### PR DESCRIPTION
**Pull request by jiminys**

### CODE REVIEW

**Comment by pablodenadai** [comment]
~~Nice one!~~

**Comment by jiminys** [comment]
Not so nice, the html compressor doesn't play nicely with ng2 syntax....

```
       throw 'Parse Error: ' + html;
       ^
Parse Error: <a [routerLink]="['Home']">Home</a></li>
               <li><a [routerLink]="['Colours']">Colours</a></li>
               <li><a [routerLink]="['Typography']">Typography</a></li>
               <!--<li><a ui-sref="typography">Typography</a></li>-->
               <!--<li><a ui-sref="buttons">Buttons</a></li>-->
               <!--<li><a ui-sref="forms">Form elements</a></li>-->
               <!--<li><a ui-sref="layout">Layout/Grid</a></li>-->
           </ul>
       </div>
   </div>
/div>
```

**Comment by pablodenadai** [comment]
Okay no worries. Are you having a look at it? Maybe add some tests too. Cheers.

**Comment by jiminys** [comment]
Yeah, I'll have a play tomorrow. I'll add some ng2 syntax to your test suite and reuse.

I noticed some funnies with crlf and the style regex BTW; if test.js is on windows then it doesn't select the multi line URL blocks.

Feel free to rollback if you want - I was a bit quick to commit (without test anyway!)

**Comment by pablodenadai** [comment]
All good, let me know how it goes :-)

**Pull request merged**
