### PR TITLE
added SCSS precompilation support; added node-sass as dependency

### PR DESCRIPTION
**Pull request by mike-shtil**
Tested to work for me with real SCSS. May require extra tweaking for cases of complex SCSS @import but it's a good base to start.

### CODE REVIEW

**Comment by mike-shtil** [comment]
added proper handling of SCSS @import

**Comment by pablodenadai** [comment]
Just need to write a test case for SCSS. Thanks

**Comment by dfenstermaker** [comment]
@mike-shtil @pablodenadai whats the reason for this PR dying off? I realize the tests are failing and thats keeping it from merging, is there needed assistance here? I need this functionality and will get the tests working if thats all that is keeping this from being merged.

**Comment by pablodenadai** [comment]
Closing in favour of #32

**Pull request closed without merging**
